name 'jenkins_server_wrapper'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures nikplugin'
depends 'java'
depends 'jenkins'
